### ISSUE TITLE
caching rules?

### ISSUE THREAD

**Issue by casouri** [kahing/catfs#11]
What is the specific rule/algorithm for caching? Is it by time/space? And could it be customized?

**Comment by kahing** [comment]
There's no customization beyond the options listed in `--help`. I don't understand the rest of the questions

**Comment by casouri** [comment]
I mean deleting cache files that have a timestamp older than, for example, a month; or set a maximum space that particular directory can use.

**Comment by kahing** [comment]
Eviction policy is LRU, and you can only set usage percentage for the entire mount point. If you don't see it under `--help`, it's not implemented
