### ISSUE TITLE
How the enable remote cache? 

### ISSUE THREAD

**Issue by SungHoHong2** [kahing/catfs#17]
Hello, I'am trying to use the catfs to test the storage on local but the cache in the remote. 
Right now I can run the cache and the storage all in local, but is there a way to enable cache as the remote? 

According to the tests in the README file implies that either the cache or the storage was running in the remote side correct? 
I am trying to use NFS in order to use the remote cache, but I don't know whether this is the right way

**Comment by SungHoHong2** [comment]
I am trying to use the cache working in the remote storage, and run the storage in the local. 
So this isn't possible for catfs?

**Comment by kahing** [comment]
the cache storage has to support xattr
