### ISSUE TITLE
Opens 50,000 pipes to self, hits EMFILE (too many open files), reads incorrect data

### ISSUE THREAD

**Issue by wjt** [kahing/catfs#18]
I am attempting to use goofys + catfs to mount a local, read-only view of an S3 bucket as follows:

```
$ /usr/local/bin/goofys -o allow_other --cache -o:allow_other:/var/cache/mirror --dir-mode 493 --file-mode 292 images-dl.endlessm.com /srv/images-dl.endlessm.com_s3
```

I'm then pointing [mirrorbits](https://github.com/etix/mirrorbits) at a subtree of this directory. It will walk all files in that tree. It's configured to never actually read the contents of any of the files (I have disabled all hashing) but as an [implementation detail](https://github.com/etix/mirrorbits/blob/eb636ee7ce3f62a2e7e7f025a89a837ec0c2e796/filesystem/hash.go#L20-L59) it will `open` every file it encounters for reading, and then immediately `close` it. 
The net effect is that every file in the tree is read in quick succession, then closed. There are 27582 files in the subtree in question.

It looks from the logs like like goofys/catfs to do some read-ahead on each file as it is opened. Unfortunately, mid-way through the scan, catfs runs out of file descriptors:

```
catfs.INFO 2018-07-13 15:30:56 ERROR - read ahead "release/3.4.5/eos-amd64-amd64/base/eos-eos3.4-amd64-amd64.180712-201651.base.img.xz.asc" failed: Too many open files (os error 24) stack backtrace:
catfs.INFO    0:     0x55ee812f12bc - backtrace::backtrace::trace::h7544cb300c8adc70
catfs.INFO    1:     0x55ee812f12f2 - backtrace::capture::Backtrace::new::h0e3ca146bdded087
catfs.INFO    2:     0x55ee81217255 - <catfs::catfs::error::RError<E>>::from::hc6f3000dd77f7864
catfs.INFO    3:     0x55ee8121aabf - catfs::catfs::file::Handle::copy::hb749b1d9c173f302
catfs.INFO    4:     0x55ee811f57dc - <F as threadpool::FnBox>::call_box::h20dacdcfe2491af7
catfs.INFO    5:     0x55ee812bcb41 - std::sys_common::backtrace::__rust_begin_short_backtrace::h69ffcb2ce386e3c5
catfs.INFO    6:     0x55ee81342d3e - panic_unwind::__rust_maybe_catch_panic
catfs.INFO                         at /checkout/src/libpanic_unwind/lib.rs:101
catfs.INFO    7:     0x55ee812c0030 - <F as alloc::boxed::FnBox<A>>::call_box::hfbaa7f762fcf229f
catfs.INFO    8:     0x55ee8133950b - alloc::boxed::{{impl}}::call_once<(),()>
catfs.INFO                         at /checkout/src/liballoc/boxed.rs:772
catfs.INFO                          - std::sys_common::thread::start_thread
catfs.INFO                         at /checkout/src/libstd/sys_common/thread.rs:24
catfs.INFO                          - std::sys::imp::thread::{{impl}}::new::thread_start
catfs.INFO                         at /checkout/src/libstd/sys/unix/thread.rs:90
catfs.INFO    9:     0x7f165f762493 - start_thread
catfs.INFO   10:     0x7f165f28dace - __clone
catfs.INFO   11:                0x0 - <unknown>
```

Even after the scan has finished and mirrorbits is shut down (so no files should be open), attempting to read most files causes this error. Looking at the output of lsof, catfs has over 100,000 FIFO fds open; they mostly come in r/w pairs with the same NODE.

```
$ sudo lsof  | grep catfs | grep FIFO | wc -l
109404
$ sudo lsof | head -n1; sudo lsof  | grep catfs | grep FIFO | head -n 10
COMMAND     PID   TID        USER   FD      TYPE             DEVICE SIZE/OFF       NODE NAME
catfs     14161            mirror    2w     FIFO               0,10      0t0     234581 pipe
catfs     14161            mirror   10r     FIFO               0,10      0t0     234783 pipe
catfs     14161            mirror   12w     FIFO               0,10      0t0     234783 pipe
catfs     14161            mirror   13r     FIFO               0,10      0t0     234785 pipe
catfs     14161            mirror   14w     FIFO               0,10      0t0     234785 pipe
catfs     14161            mirror   15r     FIFO               0,10      0t0     234786 pipe
catfs     14161            mirror   16w     FIFO               0,10      0t0     234786 pipe
catfs     14161            mirror   17r     FIFO               0,10      0t0     234790 pipe
catfs     14161            mirror   18w     FIFO               0,10      0t0     234790 pipe
catfs     14161            mirror   19r     FIFO               0,10      0t0     234794 pipe
```

Reading certain files returns EMFILE; reading others returns content of the correct length but with the contents of the wrong file. For example, `$mountpoint/release/3.4.5/eos-amd64-amd64/base/eos-eos3.4-amd64-amd64.180712-201651.base.iso.asc` is 833 bytes long (correct) but those bytes are the first 833 bytes of an adjacent file `$mountpoint/release/3.4.5/eos-amd64-amd64/base/eos-eos3.4-amd64-amd64.180712-201651.base.iso`. 

Any suggestions for how to begin debugging this? I'm afraid I have never written a line of Go or Rust in my life!

```
$ catfs --version
catfs 0.7.0
$ sha256sum $(which catfs)
306466bea43aaa2e14f980479fa49774913043bab35f6b27044e8150419ae97c  /usr/local/bin/catfs
```

despite what `catfs --version` says, it's actually https://github.com/kahing/catfs/releases/download/v0.8.0/catfs .

**Comment by wjt** [comment]
I think the FIFOs are being leaked by [`copy_splice`](https://github.com/kahing/catfs/blob/7fcbc44f6e4f1ef77da5acf8fb1d1abbca5d644f/src/catfs/file.rs#L619-L648). If either https://github.com/kahing/catfs/blob/7fcbc44f6e4f1ef77da5acf8fb1d1abbca5d644f/src/catfs/file.rs#L624 or https://github.com/kahing/catfs/blob/7fcbc44f6e4f1ef77da5acf8fb1d1abbca5d644f/src/catfs/file.rs#L631 fails, I think based on my limited knowledge of Rust's `?` operator that the function early-returns, without running the cleanup block https://github.com/kahing/catfs/blob/7fcbc44f6e4f1ef77da5acf8fb1d1abbca5d644f/src/catfs/file.rs#L640-L645

Could this be true?

**Comment by gaul** [comment]
Please retest with the latest master.

**Comment by wjt** [comment]
I cannot easily test this now because I am no longer working on the project where I encountered this bug.

**Comment by wjt** [comment]
I tried to reproduce the pattern of behaviour by mounting the same filesystem stack on my local system and walking the tree with:

```
for dirpath, dirnames, filenames in os.walk("/srv/images-dl.endlessm.com_s3"):
    for filename in filenames: 
        p = os.path.join(dirpath, filename) 
        with open(p, "r"): 
            print(p) 
```

Seems to be making good progress and `catfs` does not seem to be leaking file descriptors.

**Comment by gaul** [comment]
Great!  I am concerned about the reading of incorrect data but please open a new issue if you encounter this symptom.
