### ISSUE TITLE
version `GLIBC_2.18' not found (required by catfs)

### ISSUE THREAD

**Issue by hdnebat** [kahing/catfs#20]
I'm trying to use catfs along with goofys both latest versions as of now on centOS 7.5 , however, when i try to mount with cache enabled I receive this error:

Invalid value "/tmp/cache" for --cache: catfs: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by catfs)

the version exist with centos: glibc-2.17-222.el7.x86_64

any idea how to solve this?

**Comment by kahing** [comment]
were you using the release binary? you probably want to build from source
