### ISSUE TITLE
File appears truncated

### ISSUE THREAD

**Issue by isarandi** [kahing/catfs#22]
Scenario: a remote file changes.
Problem: While the cache content is good and up-to date, the view presented at the mountpoint (third argument to catfs) is truncated. The file is there, but it's only partially present if I display it via cat. Other times a bunch of NULL bytes appear at the end.

So the cache directory content is fine, but through the mountpoint I get garbage.

**Comment by mikkorantalainen** [comment]
Is it still possible to reproduce this issue?

**Comment by isarandi** [comment]
Sorry, I no longer use this program or have the configuration set up.

**Comment by hamann** [comment]
Just ran into the same issue with 0.7.0
