### ISSUE TITLE
On a clean Ubuntu box, fails to build with "the trait `std::default::Default` is not implemented for `std::path::PathBuf`"

### ISSUE THREAD

**Issue by akitchin** [kahing/catfs#5]
sudo apt install cargo pkg-config libfuse-dev && cargo install catfs

error[E0277]: the trait bound `std::path::PathBuf: std::default::Default` is not satisfied
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/catfs-0.4.0/src/evicter/dir_walker.rs:23:23
   |
23 |             cur_path: Default::default(),
   |                       ^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `std::path::PathBuf`
   |
   = note: required by `std::default::Default::default`

error: aborting due to previous error

error: failed to compile `catfs v0.4.0`, intermediate artifacts can be found at `/tmp/cargo-install.A640JAvfiIKV`

Caused by:
  Could not compile `catfs`.

**Comment by kahing** [comment]
Your rust version is probably too old. Try with an least 1.18
